CREATE TABLE Student (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Class_id INTEGER,
  Country_id INTEGER,
  Name VARCHAR(255),
  Date_of_birth DATE,
  CreatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ModifiedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (Class_id) REFERENCES Class(Id),
  FOREIGN KEY (Country_id) REFERENCES Countries(Id)
);


CREATE TABLE Class (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Class_name VARCHAR(100)
);


CREATE TABLE Countries (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Name VARCHAR(100)
);
